Update build app page
odk-x/docs pull request #147
Opened 2021-10-07 09:15 UTC by EstherPhebe

addresses odk-x/tool-suite-X#207

#### What is included in this PR?
1. Remove reference to grunt file for tables as it is currently not working
2. Add Skip logic table as List and Detail view example

#### What new issues will need to be opened because of this PR?
none
#### What is left to be done in the addressed issue?
none
#### What problems did you encounter?
none

2021-10-07 13:45 UTC, elmps2018 reviewed
This looks great (so far as I could tell! Someone who knows tables code better should also check!)

2021-10-07 13:45 UTC, elmps2018 commented on odkx-src/build-app.rst
> +    - :th:`collect-forms`
I am not sure all these folders are needed... forms definitely. Are the others needed for tables? I mostly use survey so not sure.

2021-10-17 20:53 UTC, wbrunette commented on odkx-src/build-app.rst
> +After building your own application, you may choose to delete all the examples forms and configurations before pushing your files to your device; as the files can be very large and take up a lot of s
I am referring to deleting all the example forms. It was automated to avoid confusion (you should test it).

2021-10-17 20:54 UTC, wbrunette commented
@EstherPhebe I added comments to Caroline's review

2021-11-03 15:26 UTC, elmps2018 requested changes
One tiny copy edit otherwise looks good to me!

2021-11-03 15:26 UTC, elmps2018 commented on odkx-src/build-app.rst
> +Open the terminal and type *grunt empty*, this removes all the files and creates an empty app-designer folder to work with.
Suggest adding "To delete all the example forms and configurations, open"

2021-11-03 15:26 UTC, elmps2018 commented on odkx-src/build-app.rst
> +:guilabel:`grunt clean` : Wipes the device of all ODK-X data
for consistency add period.

2021-11-03 15:27 UTC, elmps2018 commented
@EstherPhebe there is now a conflict too...

2021-11-04 17:15 UTC, EstherPhebe commented
> @EstherPhebe there is now a conflict too...

I'll fix that.

2021-11-10 14:51 UTC, EstherPhebe commented
I'm sorry about the weird commit history. I did a git rebase to fix the conflict

2021-11-11 15:04 UTC, elmps2018 approved these changes

2021-11-11 15:05 UTC, elmps2018 commented
@EstherPhebe this looks fabulous to me!

2021-11-11 19:15 UTC, merged