fix doc description in app-designer-overview
odk-x/docs pull request #286
Opened 2024-03-21 18:34 UTC by Chinex-Boroja

#### What is included in this PR?

1. I made line-edits in `app-designer-overview.rst` which is for https://github.com/odk-x/tool-suite-X/issues/207
2. Changed  `future` to `in future` for a better description

2024-03-21 18:52 UTC, Chinex-Boroja commented
Hi @wbrunette @elmps2018 you take a look at the new changes and review. Thank you

2024-03-21 20:34 UTC, wbrunette requested changes
I just noticed the way it reads is slightly off as it could be interpreted as list and detailed views are also in figure.  Perhaps a better solution is to simply remove graph from the list and just have list views and detail views.

2024-03-21 21:34 UTC, Chinex-Boroja commented
> I just noticed the way it reads is slightly off as it could be interpreted as list and detailed views are also in figure. Perhaps a better solution is to simply remove graph from the list and just have list views and detail views.

Hi @wbrunette, I just made a fix, you can kindly review. Thank you

2024-03-21 23:45 UTC, wbrunette commented on src/app-designer-overview.rst
> +  - :ref:`Preview <app-designer-overview-preview>` (shown above) - used to preview `ODK-X Survey <https://docs.odk-x.org/survey-using/>`_ forms and ODK-X Tables list-, detail- and graph- views (in fu
Just graph views got dropped (needed to be rewritten) ... detail, list, and map views make up the essence of tables.

2024-03-23 12:17 UTC, Chinex-Boroja commented on src/app-designer-overview.rst
> +  - :ref:`Preview <app-designer-overview-preview>` (shown above) - used to preview `ODK-X Survey <https://docs.odk-x.org/survey-using/>`_ forms and ODK-X Tables list-, detail- and graph- views (in fu
@elmps2018 I have made the fix. Can you kindly review?

2024-03-23 17:44 UTC, elmps2018 commented on src/app-designer-overview.rst
> +  - :ref:`Preview <app-designer-overview-preview>` (shown above) - used to preview `ODK-X Survey <https://docs.odk-x.org/survey-using/>`_ forms and ODK-X Tables list-, detail- and graph- views (in fu
@Chinex-Boroja the text looks good to me, but @wbrunette are the other types in the future?

2024-03-25 14:39 UTC, wbrunette requested changes

2024-03-25 14:39 UTC, wbrunette commented on src/app-designer-overview.rst
> +  - :ref:`Preview <app-designer-overview-preview>` (shown above) - used to preview `ODK-X Survey <https://docs.odk-x.org/survey-using/>`_ forms and ODK-X Tables list-views and detail-views (in the fu
"In the future" is not needed as graph views was the only one in future and was confusing. List and Detail views are both available and are NOT in the future.

2024-03-25 21:30 UTC, wbrunette approved these changes

2024-03-25 21:30 UTC, merged