Modify git clone to perform shallow clone
odk-x/docs pull request #91
Opened 2021-04-16 09:50 UTC by Shubhamr837

What is included in this PR?
There was an error in step numbering that has been corrected.
git clone command for sync-endpoint is modified to perform shallow clone.

2021-04-16 09:54 UTC, Shubhamr837 commented
Hi @linl33 ! I modified the sync-endpoint-mannual-setup doc. But I am confused about the changes to be made in the yml files at https://github.com/odk-x/docs/tree/master/odkx-src/files. The cloud-init files have command clone the sync-endpoint-default-setup repository ,should we modify that? Please guide me about what changes are to be made.

2021-04-17 02:26 UTC, wbrunette commented
@Shubhamr837 you are looking at the docker image setup files, the git clone happens when the user runs the install after the image is created because user input is needed. Here is a link
https://github.com/odk-x/sync-endpoint-default-setup/blob/master/init-odkx-sync-endpoint.py#L153

2021-04-17 05:27 UTC, linl33 requested changes
I thought the cloud-init scripts also clone sync-endpoint. You don't need to make changes to the cloud-init scripts.

2021-04-17 05:27 UTC, linl33 commented on odkx-src/sync-endpoint-manual-setup.rst
> +     The above command performs a shallow clone of the sync-endpoint Github repository. To perform a full clone remove :guilabel:`--single-branch --depth=1` from the command.
It is a git repository, not a GitHub repository. Or you could specify that it's a GitHub git repository.

2021-04-17 08:16 UTC, Shubhamr837 commented
Thanks @linl33 I have made the changes , please review

2021-04-20 05:11 UTC, linl33 commented on odkx-src/sync-endpoint-manual-setup.rst
> +     The above command performs a shallow clone of the sync-endpoint Github git repository. To perform a full clone remove :guilabel:`--single-branch --depth=1` from the command.
> sync-endpoint Github git repository

It should be capitalized as GitHub

2021-04-20 10:35 UTC, Shubhamr837 commented
Thanks @linl33 I have made the changes. Please review and suggest if any other change is needed.

2021-05-08 23:53 UTC, wbrunette approved these changes

2021-05-08 23:53 UTC, merged